name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run full test suite
        run: bun run prepack

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build for release
        run: bun run build
        
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Update package.json version
        run: |
          npm install
          npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
          
      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref.replace('refs/tags/', ''),
              name: `Release ${{ steps.version.outputs.VERSION }}`,
              body: `## Changes in v${{ steps.version.outputs.VERSION }}

            See [CHANGELOG.md](https://github.com/SubtleTools/move-ts-file/blob/main/CHANGELOG.md) for details.

            ## Installation

            \`\`\`bash
            npm install -g move-ts-file@${{ steps.version.outputs.VERSION }}
            \`\`\`

            Or use with npx:
            \`\`\`bash
            npx move-ts-file@${{ steps.version.outputs.VERSION }} <source> <destination>
            \`\`\``,
              draft: false,
              prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}
            });
            console.log(`Created release: ${release.html_url}`);
          
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance
        
      - name: Update GitHub Pages documentation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docs.yml'
            });