name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        runtime: [node, bun]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup Bun (if testing with bun)
        if: matrix.runtime == 'bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies (Node)
        if: matrix.runtime == 'node'
        run: npm install
        
      - name: Install dependencies (Bun)
        if: matrix.runtime == 'bun'
        run: bun install --frozen-lockfile
        
      - name: Type check
        run: |
          if [ "${{ matrix.runtime }}" = "bun" ]; then
            bun run typecheck
          else
            npm run typecheck
          fi
          
      - name: Lint
        run: |
          if [ "${{ matrix.runtime }}" = "bun" ]; then
            bun run lint
          else
            npm run lint
          fi
          
      - name: Format check
        run: |
          if [ "${{ matrix.runtime }}" = "bun" ]; then
            bun run format:check
          else
            npm run format:check
          fi
          
      - name: Test
        run: |
          if [ "${{ matrix.runtime }}" = "bun" ]; then
            bun run test
          else
            npm run test
          fi
          
      - name: Build
        run: |
          if [ "${{ matrix.runtime }}" = "bun" ]; then
            bun run build
          else
            npm run build
          fi
          
      - name: Test CLI (Node)
        if: matrix.runtime == 'node'
        run: |
          mkdir -p test-cli/src
          echo 'export const test = "hello";' > test-cli/src/test.ts
          echo 'import { test } from "./test";' > test-cli/src/main.ts
          cd test-cli
          node ../bin/move-ts-file.js src/test.ts src/utils/test.ts
          # Verify the import was updated
          if ! grep -q 'from "./utils/test"' src/main.ts; then
            echo "CLI test failed - import not updated correctly"
            exit 1
          fi
          cd ..
          rm -rf test-cli
          
      - name: Test CLI (Bun)
        if: matrix.runtime == 'bun'
        run: |
          mkdir -p test-cli/src
          echo 'export const test = "hello";' > test-cli/src/test.ts
          echo 'import { test } from "./test";' > test-cli/src/main.ts
          cd test-cli
          bun ../bin/move-ts-file.js src/test.ts src/utils/test.ts
          # Verify the import was updated
          if ! grep -q 'from "./utils/test"' src/main.ts; then
            echo "CLI test failed - import not updated correctly"
            exit 1
          fi
          cd ..
          rm -rf test-cli